#!/bin/sh
. "$(dirname "$0")/_/husky.sh"
echo "pre-commit:"
export NODE_OPTIONS="--max-old-space-size=8000"
cd client/chatgpt/ChatGPT.Client/ChatGPTClientApp
echo "checking client changes."
if git diff --name-only HEAD | grep 'client/chatgpt/ChatGPT\.Client/ChatGPTClientApp'; then
  npx --no-install tsc -p tsconfig.json --noEmit
  npx --no-install lint-staged
else
  echo "no client changes detected."
fi
