overwrite: true
schema:
  - ./src/proxy/schema.graphql
  - http://localhost:3001/graphql/
  # - https://api.dev.xorgx.tech/graphql/
# extensions:
#   endpoints:
#     default:
#       url: "https://fms.api.dev.kufosoft.com/graphql"
#       headers:
#         Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDEiLCJsb2dpbl9wcm92aWRlciI6IlRydXN0ZWQifQ.MLw-_WPkvIsTI_QICxR8tiOJhGRSGWI3bVNoXUm1Fhw
documents:
  - "./src/**/*.graphql"
  - "!./src/**/*.test.graphql"
  - "!./src/**/test.graphql"
generates:
  ./src/proxy/.generated/type.ts:
    plugins:
      - typescript
      - typescript-operations
      - typed-document-node
    config:
      declarationKind: "interface"
      documentMode: "graphQLTag"
      defaultScalarType: "any"
      scalars:
        ChinesePhoneNumberType: "string"
        DateTime: "Date"
        Decimal: "number"
        Long: "BigInt"
        ObjectId: "string"
      documentVariableSuffix: "Gql"
      fragmentVariableSuffix: "Gql"
  ./src/proxy/.generated/apollo-helpers.ts:
    plugins:
      - typescript-apollo-client-helpers
config:
  declarationKind: "interface"
  enumsAsTypes: false
