version: '3.7'

name: xorgx

services:
  identity-dev-xorgx-tech:
    hostname: identity.dev.xorgx.tech
    container_name: identity.dev.xorgx.tech
    image: xorgx/identity:latest
    entrypoint: ["node", "main.js"]
    env_file:
      - .env.development
    volumes:
      - ../../../dev_env/certs:/app/certs:ro
    build: 
      context: "."
      args:
        - NODE_ENV=development
    ports:
      - 3001:3001
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 3001 || exit 1"]
      interval: 10s  
      timeout: 5s  
      retries: 3  
    networks:
      - net
    # depends_on:
    #   - mongo
    #   - redis

networks:
  net:
    name: dev
    external: true
