version: '3.7'

name: xorgx

services:
  docs:
    hostname: docs.dev.xorgx.tech
    container_name: docs.dev.xorgx.tech
    profiles:
      - "client/docs"
    image: xorgx/docs:latest
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.docs-dev-xorgx-tech.service=docs-dev-xorgx-tech"
      - "traefik.http.routers.docs-dev-xorgx-tech.entrypoints=https"
      - "traefik.http.routers.docs-dev-xorgx-tech.tls=true"
      - "traefik.http.routers.docs-dev-xorgx-tech.rule=Host(`docs.dev.xorgx.tech`)"
      - "traefik.http.services.docs-dev-xorgx-tech.loadbalancer.server.port=4003"
      - "traefik.http.services.docs-dev-xorgx-tech.loadbalancer.server.scheme=https"
    env_file:
      - .env.development
    # volumes:
    #   - ../../dev_env/certs:/app/certs:ro
    build: 
      context: "."
      args:
        - NODE_ENV=development
    ports:
      - 4002:4002
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 4002 || exit 1"]
      interval: 10s  
      timeout: 5s  
      retries: 3  
    networks:
      - net
    
networks:
  net:
    name: dev
    external: true
