tls:
  certificates:
  - certFile: /certs/dev.xorgx.tech.crt
    keyFile: /certs/dev.xorgx.tech.key
  options:
    default:
      cipherSuites:
      - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
      - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
      - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
      - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
      - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
      - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
      sniStrict: false
      minVersion: VersionTLS11
      maxVersion: VersionTLS13
  stores:
    default:
      defaultCertificate:
        certFile: /certs/dev.xorgx.tech.crt
        keyFile: /certs/dev.xorgx.tech.key
http:
  middlewares:
    compress:
      compress:
        excludedContentTypes:
        - audio/aac
        - audio/mp3
        - audio/mpeg
        - audio/ogg
        - audio/wav
        - audio/webm
        - video/mp4
        - video/mpeg
        - video/ogg
        - video/webm
        - image/bmp
        - image/gif
        - image/jpeg
        - image/png
        - image/webp
        - application/zip
        - application/gzip
        - application/x-rar-compressed
        - application/octet-stream
